### PR TITLE
removed back navigation from android controller

### PR DESCRIPTION
**Pull request by richardscholten73**
Hello @alexziskind1 ,

Could you review this pr?

Removed the back navigation from the android controller method "resumeWithUrl".
Not sure why it was there, it was causing undesired navigation after login/logout.
For example the user got a redirect back to the last page they visited after logout. If this was a page with authorization guard you were immediately asked to login again (after logging out)

The ios container does not contain a back navigation in this method and works as expected.

Not sure what the impact is on other projects/situations. In my opinion the back navigation should not be part of the library, it is part of business logic belonging to the individual project. Any navigation should be done by the developer in the completion method or something similar.

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
(android only)
After login/logout the app redirects back to the previously visited page page

## What is the new behavior?
After login/logout the app opens on the current page (no back navigation)

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by alexziskind1** [comment]
Hey Richard, thanks for the PR. Have you been able to review this with google/ms/facebook and angular/core/vue demo apps?

**Comment by richardscholten73** [comment]
> Hey Richard, thanks for the PR. Have you been able to review this with google/ms/facebook and angular/core/vue demo apps?

Tested this with identityServer and demo-angular on ios and android

**Comment by richardscholten73** [comment]
@alexziskind1  Any idea when you will be able to review this PR?

I tested this with identityserver/ms/google/facebook in the android-angular demo.
Also tested with vue and core demo's, but they don't have a authorized page (nothing to test)

All work as expected

**Comment by alexziskind1** [comment]
Thanks for the PR and the testing, Richard.  
I will be able to do a round next week and hopefully have everything merged by then.

**Comment by richardscholten73** [comment]
> Thanks for the PR and the testing, Richard. I will be able to do a round next week and hopefully have everything merged by then.
> […](#)
> On Nov 5, 2019, at 6:44 AM, Richard Scholten ***@***.***> wrote: ﻿ @alexziskind1 Any idea when you will be able to review this PR? I tested this with identityserver/ms/google/facebook in the android-angular demo. Also tested with vue and core demo's, but they don't have a authorized page (nothing to test) All work as expected — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Great! 
Could you perhaps also review my other PR? #77 
Did the same testing on that branch.

**Pull request merged**
