### PR TITLE
fix issue #116

### PR DESCRIPTION
**Pull request by Burgov**
See #116 

I think this PR should do the trick but I'm not 100% sure how to test it. 

@alexziskind1 can you verifiy?

### CODE REVIEW

**Comment by alexist** [comment]
To reproduce the issue, you juste have to put page router outlet inside à layout : 
<GridLayout rows="1"
            columns="1">
    <page-router-outlet></page-router-outlet>
</GridLayout>

With current version of this plugin, authentication with a TnsOaProvider (which delegate to SFSafariViewController), you will get an blank page in safari with the title "Website name"

**Comment by alexziskind1** [comment]
Thank for the PR @Burgov.

**Comment by Burgov** [comment]
@alexziskind1 any chance you can create a new release on npm?

**Comment by alexziskind1** [comment]
> @alexziskind1 any chance you can create a new release on npm?

This is now published

**Pull request merged**
