### PR TITLE
added identityserver provider and logout procedure

### PR DESCRIPTION
**Pull request by richardscholten73**
added logout procedure

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by alexziskind1** [comment]
Hi Richard - thanks for the PR. It seems the Travis CI build is failing for this PR - could you please check?

**Comment by richardscholten73** [comment]
Hi Alexander,

Build is fixed now.
Did not get this build error on my local environment (works on my machine).
Type checking is probably more strict in Travis CI?

I also added getLogoutUrlStr to the google provider.
Google provides a "continue" parameter, but this does not seem to work for native apps (no response). So i did not implement this part.
Callback "completion" is only called when the browser is manualty closed.
This is fine by us. I would rather have my provider (identityserver,google,facebook,etc) inform me that i am logged out than a native app.

I hope you can soon find the time to review this pr and merge it into master.

Kind regards,
Richard

**Comment by alexziskind1** [comment]
Thanks Richard!

**Comment by alexziskind1** [comment]
Richard, I've stubbed out a section in the README for IdentityServer setup, could you please add something there?

**Pull request merged**
