### PR TITLE
static handleIncomingUrl

### LINKED ISSUE #138: Oauth 2 - Google - After Sigin not redirected back to app
### Which platform(s) does your issue occur on?
- Anddroid - Angular
- iOS/Android versions 
- What type of device - Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI:  7.0.4
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
I have integrated the latest version of Oauth -2. After I hit the signin button for Google, it prompt me for login(already loggedin users) on chrome. After I select the login, the browser does not come back to App. It just opens google.com.

I am using exactly same code mentioned in the demo app except the client id and other keys. This used to work for me earlier, it suddenly stopped working. This is working fine on my phone, not working on emulator.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

### PR DESCRIPTION
**Pull request by OniQ**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
Uncaught TypeError: this.handleIncomingUrl is not a function

## What is the new behavior?

Fixes #138

### CODE REVIEW

**Comment by alexziskind1** [comment]
I'm closing this as the original issue #138 is Android related and this PR targets iOS only. Furthermore, after testing, there is no such issue that I could reproduce on iOS.

**Comment by JohanBeumer** [comment]
@alexziskind1 Please consider reopening this PR. I'm getting the error only on iOS, but only in my own project in which I also use firebase. Putting the solution of this PR in place solves it.

However in the community chat of 23rd september starting at minute 13 @NathanWalker and @cjohn001 discussed [#135](https://github.com/alexziskind1/nativescript-oauth2/issues/135) which is exactly what I am experiencing. So maybe there is a better solution?

Unfortunately I'm not familiar enough with delegates to be able to put the solution @NathanWalker suggests in place. Any help with that is appreciated!

Lastly I searched the code of the repo and `handleIncomingUrl` only is in the sources :
demo-angular/node_modules/nativescript-oauth2/delegate/delegate.ios.js
demo-angular/node_modules/nativescript-oauth2/delegate/index.ios.js
src/delegate/index.ios.js
src/delegate/index.ios.ts
so it must be an iOS thing, right?

**Comment by hammelev** [comment]
@alexziskind1 please open the PR again. The current version breaks my application when used together with the firebase plugin on iOS when attempting to login. Adding this PR fixes the error and allows my application to login.

**Comment by nc-kfl** [comment]
Nice work with this package for NativeScript @alexziskind1 and @OniQ. What are the changes that this can be reopned? On my project we have problems with the firebase plugin too and the fixed in this pull-request has shown to fix it.

**Pull request closed without merging**
